import Provider from '@/components/Provider';
import StyledComponentRegistry from '@/lib/registry';
import QueryClientProvider from '@/services/QueryClientProvider';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
        <body>
          <StyledComponentRegistry>
            <QueryClientProvider>
              <Provider>{children}</Provider>
            </QueryClientProvider>
          </StyledComponentRegistry>
        </body>
    </html>
  );
}
