import type { Metadata } from 'next';
import Provider from './providers/Provider';
import QueryClientProvider from './providers/QueryClientProvider';
import StyledComponentsProvider from './providers/StyledComponentsProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <StyledComponentsProvider>
          <QueryClientProvider>
            <Provider>{children}</Provider>
          </QueryClientProvider>
        </StyledComponentsProvider>
      </body>
    </html>
  );
}
