const getLetteringFontsById = (id: string): string[] => {
  const letteringFontMap: Record<string, string[]> = {
    '1': [
      'BBB003',
      'Ownglyph Kundo',
      'Diphylleia',
      'DOSGothic',
      'KoreanCNMM',
      'LeeSeoyun',
      'MapoDacapo',
      'Ownglyph Baek Subin',
      'Nelna Yesam',
    ],
    '2': [
      'Ownglyph Kundo',
      'Diphylleia',
      'DOSGothic',
      'KoreanCNMM',
      'LeeSeoyun',
      'MapoDacapo',
      'Ownglyph Baek Subin',
      'Nelna Yesam',
      'White Angelica',
    ],
    '3': [
      'BBB003',
      'Ownglyph Kundo',
      'Diphylleia',
      'DOSGothic',
      'KoreanCNMM',
      'LeeSeoyun',
      'MapoDacapo',
      'Ownglyph Baek Subin',
      'Nelna Yesam',
      'White Angelica',
    ],
    '4': [
      'Ownglyph Kundo',
      'Diphylleia',
      'DOSGothic',
      'KoreanCNMM',
      'LeeSeoyun',
      'MapoDacapo',
      'Ownglyph Baek Subin',
      'Nelna Yesam',
    ],
    '5': [
      'BBB003',
      'Ownglyph Kundo',
      'Diphylleia',
      'DOSGothic',
      'KoreanCNMM',
      'LeeSeoyun',
      'MapoDacapo',
      'Ownglyph Baek Subin',
      'White Angelica',
    ],
    '6': [
      'BBB003',
      'Ownglyph Kundo',
      'Diphylleia',
      'DOSGothic',
      'KoreanCNMM',
      'LeeSeoyun',
      'MapoDacapo',
      'Ownglyph Baek Subin',
      'Nelna Yesam',
      'White Angelica',
    ],
    '7': [
      'BBB003',
      'Ownglyph Kundo',
      'Diphylleia',
      'DOSGothic',
      'KoreanCNMM',
      'LeeSeoyun',
      'MapoDacapo',
      'Ownglyph Baek Subin',
      'Nelna Yesam',
    ],
    '8': [
      'BBB003',
      'Ownglyph Kundo',
      'Diphylleia',
      'DOSGothic',
      'KoreanCNMM',
      'White Angelica',
    ],
  };

  return letteringFontMap[id] ?? ['Ownglyph Kundo'];
};

export default getLetteringFontsById;
